// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oftwtytbgjyvuuzmlhbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdHd0eXRiZ2p5dnV1em1saGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4OTQ4MTMsImV4cCI6MjA3ODQ3MDgxM30.4GDiHvIRU4dk6WPLTHGqbr4iqzYMxaC9ApWTHJHbTNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});